### ISSUE TITLE
How To Fix sqlalchemy.exc.TimeoutError

### ISSUE THREAD

**Issue by rider8581** [alephdata/ingest-file#251]
Hello
Thank you for your contribution.
I am using the latest version(3.16.1) of docker image of this project and facing the following error when I ingest the file.
![image](https://user-images.githubusercontent.com/52605718/162568633-32916ffc-9304-4945-84ee-d1889bd9c9f1.png)
Could you kindly guide me how I can fix this?
I am using docker image and it used to be restarted cause of this error.
Thank you

**Comment by rider8581** [comment]
This is what I see in aleph web console after the ingest finishes.
![image](https://user-images.githubusercontent.com/52605718/162683117-a986113a-43a4-4aae-834d-4799d46c272c.png)

**Comment by sunu** [comment]
Hi @rider8581, do you encounter this error while ingesting a specific set of files or while ingesting any file in general?

**Comment by rider8581** [comment]
It happens in some big files of more than 100MB.
I suppose it happens when I upload several big files simultaneously.

**Comment by sunu** [comment]
How many workers and worker threads are you using? May be we need to expose a way to increase the default pool size of the SQLAlchemy engine in use.

**Comment by rider8581** [comment]
I am using default configuration so not sure how many threads there are.
Could you guide me how I can configure pool size when I use docker image?

**Comment by rider8581** [comment]
After checking code, I noticed WORKER_THREADS is configured to the value of cpu number (24 in my case) by default.
So I forced it limit to 5 by setting environment variable of docker container and it seems there is no error now.
But still it would be better if I configure the pool size through env or something for better performance.

**Comment by sunu** [comment]
Thanks for investigating @rider8581. I have created an issue for that. Closing this one for now.
